version: '3.3'

services:
  postgres_typeorm:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ:America/La_Paz
    ports:
      - '5433:5432'
    volumes:
      - /home/jvillafuerte/Documents/Docker/postgres_typeorm:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'

  mysql_typeorm:
    image: mysql
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - '3306:3306'
    volumes:
      - /home/jvillafuerte/Documents/Docker/mysql_typeorm:/var/lib/mysql

  phpmyadmin_typeorm:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - PMA_HOST=mysql
    ports:
      - '8080:80'
