version: '3.3'

services:
  postgres_typeorm:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ:America/La_Paz
    ports:
      - '5433:5432'
    volumes:
      - /home/jvillafuerte/Documents/Docker/postgres_typeorm:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
